### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by noraj1337** [dNetGuru/JSUNFuck#2]
Hello,

can you please, add more instruction on how to build your project and how to run it for linux users ?

Thanks

**Comment by dNetGuru** [comment]
You can either use .Net Core to compile and run this on *nix OR use Mono.
Detailed instructions on using Mono can be found here (just follow the example): http://www.mono-project.com/docs/getting-started/mono-basics/

Please re-open this if you run into any problems.
